const pizzas = [
  {
    id: 1,
    name: "Margherita",
    price30: "22.50",
    price40: "34.50",
    tags: ["ser oregano"],
  },
  {
    id: 2,
    name: "Pepperoni",
    price30: "27.50",
    price40: "39.50",
    tags: "ser salami oregano",
  },
  {
    id: 3, 
    name: "Capriciosa",
    price30: "26.50",
    price40: "38.50",
    tags: "ser szynka pieczarki oregano",
  },
  {
    id: 4,
    name: "Hawajska",
    price30: "28.50",
    price40: "40.50",
    tags: "ser szynka ananas kukurydza oregano",
  },
  {
    id: 5,
    name: "Wiejska",
    price30: "34.50",
    price40: "46.50",
    tags: "ser wędzony boczek kiełbasa cebula ogórek kiszony",
  },
  {
    id: 6,
    name: "Sielska",
    price30: "32.50",
    price40: "44.50",
    tags: "ser kiełbasa pieczarki cebula",
  },
  {
    id: 7,
    name: "Carbonara",
    price30: "33.50",
    price40: "45.50",
    tags: "ser boczek cebula jajko sadzone [spód serowy]",
  },
  {
    id: 8,
    name: "Montana",
    price30: "29.50",
    price40: "41.50",
    tags: "ser kurczak kukurydza papryka",
  },
  {
    id: 9,
    name: "Ostra",
    price30: "29.50",
    price40: "41.50",
    tags: "ser salami jalapeno pepperoni cebula czerwona",
  },
  {
    id: 10,
    name: "Mięsna",
    price30: "35.50",
    price40: "47.50",
    tags: "ser szynka boczek grillowany kurczak cebula",
  },
  {
    id: 11,
    name: "Campano",
    price30: "29.50",
    price40: "41.50",
    tags: "ser boczek pieczarki cebula czerwona",
  },
  {
    id: 12,
    name: "Broccoli",
    price30: "30.50",
    price40: "42.50",
    tags: "ser boczek brokuły jajko",
  },
  {
    id: 13,
    name: "Wege",
    price30: "29.50",
    price40: "41.50",
    tags: "ser pieczarki papryka kukurydza oliwki cebula",
  },
  {
    id: 14,
    name: "Tuna",
    price30: "33.50",
    price40: "45.50",
    tags: "ser tuńczyk jajko cebula oregano rukola [spód serowy]",
  },
  {
    id: 15,
    name: "Maizo",
    price30: "34.50",
    price40: "46.50",
    tags: "ser salami pieczarki kukurydza prażona cebulka",
  },
  {
    id: 16,
    name: "Carolina",
    price30: "31.50",
    price40: "43.50",
    tags: "ser salami oliwki rukola",
  },
  {
    id: 17,
    name: "Regina",
    price30: "32.50",
    price40: "44.50",
    tags: "ser kurczak brokuły suszone pomidory",
  },
  {
    id: 18,
    name: "Paella",
    price30: "35.50",
    price40: "47.50",
    tags: "ser krewetki chorizo pomidor koktajlowy rukola",
  },
  {
    id: 19,
    name: "Greco",
    price30: "32.50",
    price40: "44.50",
    tags: "ser bakłażan oliwki feta cebula czerwona",
  },
  {
    id: 20,
    name: "4 sery",
    price30: "33.50",
    price40: "45.50",
    tags: "mozarella gorgonzola ser wędzony feta",
  },
  {
    id: 21,
    name: "Pollo",
    price30: "34.50",
    price40: "46.50",
    tags: "ser grillowany kurczak papryka pomidor koktajlowy rukola",
  },
  {
    id: 22,
     name: "Parma",
    price30: "34.50",
    price40: "46.50",
    tags: "ser szynka parmeńska pomidor koktajlowy parmezan rukola",
  },
  {
    id: 23,
    name: "Mexicana",
    price30: "35.50",
    price40: "47.50",
    tags: "ser wołowina chorizo kukurydza jalapeño cebula czerwona",
  },
  {
    id: 24,
    name: "Rukola",
    price30: "35.50",
    price40: "47.50",
    tags: "ser kurczak gorgonzola pomidor koktajlowy rukola",
  },
  {
    id: 25,
    name: "Salmon",
    price30: "35.50",
    price40: "47.50",
    tags: "ser tosos brokuły cebula czerwona",
  },
  {
    id: 26,
    name: "Sorento",
    price30: "36.50",
    price40: "48.50",
    tags: "ser szynka parmeńska gruszka orzech włoski glazura balsamiczna",
  },
  {
    id: 27,
    name: "Nacho",
    price30: "35.50",
    price40: "47.50",
    tags: "(spód BBQ) ser wołowina jalapeño papryka nachosy",
  },
  {
    id: 28,
    name: "Mozza",
    price30: "32.50",
    price40: "44.50",
    tags: "mozarella pomidor rukola glazura balsamiczna",
  },
  {
    id: 29,
    name: "Pizza 55",
    price30: "35.50",
    price40: "47.50",
    tags: "ser szarpane żeberko cebula ogórek kiszony majonez",
  },
  {
    id: 30,
    name: "Własna kompozycja",
    price30: "35.50",
    price40: "47.50",
    tags: "ser 3 dowolne dodatki",
  },
];

const burgers = [
  {
    id: 29,
    name: "Pizza 55",
    price30: "35.50",
    price40: "47.50",
    tags: "ser szarpane żeberko cebula ogórek kiszony majonez",
  },
  {
    id: 30,
    name: "Własna kompozycja",
    price30: "35.50",
    price40: "47.50",
    tags: "ser 3 dowolne dodatki",
  },
];

export default pizzas;
